---
title: "MAthesis"
author: "Julia Joos"
date: "14 August 2017"
output: 
  pdf_document:
   # toc: true
   # toc_depth: 2
    number_sections: true
    fig_caption: true
    df_print: kable
   # fontsize: 12pt
   # geometry: margin=1in
   # documentclass: scrartcl
   # mainfont: Helvetica
    citation_package: natbib
    keep_tex: true

header-includes:
    - \usepackage{setspace}
    - \doublespacing
    
# includes:
#       before_body: titlepage.tex
    
---

```{r "setup", include=FALSE}
require("knitr")
#opts_knit$set(root.dir = "//naturkundemuseum-berlin.de/MuseumDFSRoot/Benutzer/Julia.Joos/Eigene Dateien/MA")
## on laptop: 
opts_knit$set(root.dir = "C:/Users/Jule/Documents/Uni/MA")
library(dplyr)
library(ggplot2)
library(paleoTS)
```




```{r "import data set", echo=FALSE}
#### Data basis - import data set from Excel ####
setwd("C:/Users/Jule/Documents/Uni/MA")
tidyCL<-read.csv("tortoises_tidy.csv", sep=";", header=TRUE)

#####prepare for analysis (fix column names in .csv-file after converting table from excel####
colnames(tidyCL)[6] <- "MAmin"
colnames(tidyCL)[7] <- "Mamax"
colnames(tidyCL)[17] <- "CL"
colnames(tidyCL)[18] <- "PL"
colnames(tidyCL)[21] <- "estimated"

tidyCL <-  tidyCL %>%
  mutate(Age= ((MAmin)+(as.numeric(Mamax)))/2)

####### import extant data ####
extant <- read.csv("MFN_testudinidae.csv", sep=";", header=TRUE, dec=".", na.strings = "NA", stringsAsFactors=FALSE)  # file: MFN_testudinidae.csv

colnames(extant)[5] <- "SCL"
colnames(extant)[11] <- "PL"
colnames(extant)[12] <- "PLmid"



Extant <- extant %>%
  mutate(CL = SCL * 10, PL=PL*10, PLmid=PLmid*10) 
```


```{r "estimating CL from PL", echo=FALSE, results='asis'}
CLPLtidy <- tidyCL %>%
  filter(!is.na(CL) & !is.na(PL)) %>%
  dplyr::select(Taxon, CL, PL, size, Age, Island, Continent, Genus) %>%
  mutate(ratio=CL/PL) %>%
  group_by(Taxon) %>% #to show ratios per Taxon, leave out to get a total ratio
  summarise(meanRatio=round(mean(ratio),2), sdRatio=round(sd(ratio),2), n=n(), min=min(ratio), max=max(ratio))

CLPLextant <- Extant %>%
  filter(!is.na(CL) & !is.na(PL)) %>%
  dplyr::select(Taxon=Species, CL, PL, PLmid, Island, Continent, Genus) %>%
  mutate(ratio=CL/PL, ratioMid=CL/PLmid)
  #group_by(Taxon) %>% #to show ratios per Taxon, leave out to get a total ratio
  #  summarise(meanRatio=round(mean(ratio),2), sdRatio=round(sd(ratio),2), n=n(), min=min(ratio), max=max(ratio))

Ratio <- CLPLextant %>%
  summarise(meanRatio=round(mean(ratio),2), sdRatio=round(sd(ratio),2), n=n(), min=min(ratio), max=max(ratio))

RatioSpecies <- CLPLextant %>%
  group_by(Taxon) %>% #to show ratios per Taxon, leave out to get a total ratio
  summarise(meanRatio=round(mean(ratio),2), sdRatio=round(sd(ratio),2), n=n(), min=min(ratio), max=max(ratio))


fossil <- tidyCL %>%
  mutate(Taxon=as.character(Taxon), Island=as.character(Island), Continent=as.character(Continent), estimated=as.character(estimated), Genus=as.character(Genus)) %>%
  dplyr::select(Taxon, CL, PL, size, estimated, Age, Island, Continent, Genus)
  
modern <- Extant %>%
  dplyr::select(Taxon=Species, CL, PL, estimated, Age, Island, Continent, Genus)

All <- bind_rows(modern, fossil)

testRatio <- All %>% #tidyCL
  dplyr::select(Taxon, CL, PL, size, estimated, Age, Island, Continent, Genus) %>%
  mutate(extraCL = PL*Ratio$meanRatio) %>%
  dplyr::select(Taxon, CL, extraCL, PL, size, estimated, Age, Island, Continent, Genus)

testRatio$CL[is.na(testRatio$CL)] <- testRatio$extraCL[is.na(testRatio$CL)]
```


```{r "Bin data", echo=FALSE}

PleiPlio <- testRatio %>% #testRatio or tidyCL 
  filter(Age < 11.000)

PleiPlio$bin <- cut(PleiPlio$Age, c(0, 0.000001, 0.0117, 0.126, 0.781, 2.588, 3.6, 5.332, 11.608))

EpochBins <- as.vector(c("Modern", "Holocene", "Upper Pleistocene", "Middle Pleistocene", "Lower Pleistocene", "Upper Pliocene", "Lower Pliocene", "Upper Miocene"))




MeanBins <- as.vector(c((0+0.000001)/2, (0+0.0117)/2, (0.0117+0.126)/2, (0.126+0.781)/2, (0.781+2.588)/2,(2.588+3.6)/2, (3.6+5.332)/2, (5.332+11.608)/2))

Bins <- PleiPlio %>%
  select(bin) %>%
  group_by(bin) %>%
  summarise(nIndividuals=n())

BinsSpecies <- PleiPlio %>%
  select(bin, Taxon) %>%
  group_by(bin, Taxon) %>%
  summarise(nSpecies=n()) %>%
  summarise(nSpecies=n())


BinsGenera <- PleiPlio %>%
  select(bin, Genus) %>%
  group_by(bin, Genus) %>%
  summarise(nGenera=n()) %>%
  summarise(nGenera=n())

bin <- as.vector(unique(Bins$bin))



BINS <- data.frame(bin, EpochBins, MeanBins) %>%
  merge(Bins) %>%
  merge(BinsSpecies) %>%
  merge(BinsGenera) %>%
  arrange(MeanBins)

BINS$EpochBins = factor(BINS$EpochBins, levels=c("Modern", "Holocene", "Upper Pleistocene",
                                                             "Middle Pleistocene", "Lower Pleistocene",
                                                             "Upper Pliocene", "Lower Pliocene",
                                                             "Upper Miocene"))

#BINS <- read.table("timebins.txt", sep="\t", header=TRUE)

#kable(Bins, caption="Time bins with corresponding sample sizes (individuals)")

kable(BINS, caption="Time bins with age range, epoch name, mean age and corresponding sample sizes (on individual, species and genus level)")

PleiPlioCL <- PleiPlio %>%
  merge(BINS)

SUM <- PleiPlioCL %>%
  group_by(MeanBins) %>%
  summarise(n=n())
```


```{r "Map fossil occurrences", echo=FALSE, fig.cap="Map displaying all fossil occurrences of testudinids, with color indicating whether relevant literature was available (black if not) and if it was, whether body size data was available or not (yes and no, respectively)."}

CL <- tidyCL %>%
#  filter(Age < 11.000) %>%
  dplyr::select(Locality, Genus, Taxon, Latitude, Longitude, Country, Age) %>%
  group_by(Locality) %>%
  mutate(count= n())


FossilOccurrences<-read.csv("tortoises_occurrences.csv", sep=";", header=TRUE)

FossOcc <- FossilOccurrences %>%
  mutate(Age= (as.numeric(as.character(MA.min)) + as.numeric(as.character(Ma.max)))/2) %>%
  select(Locality, Country, Latitude, Longitude, Age, Genus, Taxon, CL) %>%
#  merge(tidyCL) %>%
  group_by(Locality) %>%
  mutate(count= n(), Longitude=as.numeric(as.character(Longitude)))


#na <- FossOcc[!complete.cases(FossOcc),]

#OccMap <-  merge(Map, FossOcc, by="Locality", incomparables=TRUE) %>%
#  distinct()
  



mapWorld <- borders("world", colour="azure3", fill="azure3") # create a layer of borders, run line at the beginning (before loading plotly)

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


mapOc <- FossOcc %>%
  ggplot(aes(Longitude, Latitude)) +# borders("world", ylim = c(-60, 90)) +
  mapWorld +
  theme_classic() +
  geom_point(data=FossOcc, (aes(as.numeric(Longitude), Latitude, colour=FossOcc$CL))) +
  geom_point(data=CL,(aes(Longitude, Latitude, colour="yes"))) +
  scale_colour_manual(values=cbbPalette)

#unique(FossOcc$CL)

mapOc

# require(plotly)
# ggplotly(mapOc)



```


```{r "Map body size data set", echo=FALSE, fig.cap="Map displaying all localities for which body size data for testudinids was available in the literature. Size of points denotes sample size, color denotes approximate age."}


tidyCL$bin <- cut(tidyCL$Age, c(0, 0.000001, 0.0117, 0.126, 0.781, 2.588, 3.6, 5.332, 11.608,33.9, 56.000))


Bins <- tidyCL %>%
  select(bin) %>%
  group_by(bin) %>%
  summarise(n=n())


bin <- as.vector(unique(Bins$bin))
EpochBins <- as.vector(c("Holocene", "Upper Pleistocene", "Middle Pleistocene", "Lower Pleistocene", "Upper Pliocene", "Lower Pliocene", "Upper Miocene", "Oligocene", "Eocene"))

MeanBins <- as.vector(c((0+0.0117)/2, (0.0117+0.126)/2, (0.126+0.781)/2, (0.781+2.588)/2,(2.588+3.6)/2, (3.6+5.332)/2, (5.332+11.608)/2, (11.608+33.9)/2, (33.9+56.0)/2 ))


bin <- as.vector(unique(Bins$bin))

BINS <- data.frame(bin, EpochBins, MeanBins) #


#BINS <- data.frame(bin, EpochBins, MeanBins) #
#BINS <- read.table("timebins.txt", sep="\t", header=TRUE)


MapCL <- tidyCL %>%
  merge(BINS) %>%
#  filter(Age < 11.000) %>%
#  filter(Latitude != "-") %>%
  dplyr::select(Genus, Taxon, Latitude, Longitude, Country, CL, PL, MeanBins, size) %>%
  group_by(Latitude) %>%
  mutate(count= n()) 


mapWorld <- borders("world", colour="azure3", fill="azure3") # create a layer of borders, run line at the beginning (before loading plotly)


mapCL <- MapCL %>%
  ggplot(aes(Longitude, Latitude)) +# borders("world", ylim = c(-60, 90)) +
  mapWorld +
  theme_classic() +
  geom_point(aes(Longitude, Latitude,size=count, colour=MeanBins)) +  #colour=size, 
  scale_colour_gradientn(colors=c("orange", "red", "purple", "blue", "green"))



mapCL


```




```{r "Get overview over sample sizes", echo=FALSE, include=FALSE}
OverviewSpecies <- PleiPlioCL %>%
  filter(EpochBins != "Modern") %>%
  group_by(EpochBins, Taxon) %>%
  summarise(n=n())

OverviewSpeciesFossil <- PleiPlioCL %>%
  filter(EpochBins != "Modern") %>%
  group_by(Taxon) %>%
  summarise(n=n())

#write.table(OverviewSpecies,file="OverviewSpeciesSampleSize.txt", sep="\t", row.names = FALSE) 


OverviewGeneraTime <- PleiPlioCL %>%
  group_by(EpochBins, Genus) %>%
  summarise(n=n())

OverviewGenera <- PleiPlioCL %>%
  group_by(Genus) %>%
  summarise(n=n())

```







```{r "Histograms of body size data", echo=FALSE, fig.cap="Distribution of body site data per time bin"}


HistCLModern <- PleiPlioCL %>%
  filter( !is.na(CL)) %>%
  filter(EpochBins == "Modern") %>%
  ggplot(aes(CL)) + geom_histogram(binwidth=10, col="black", fill="gray") + facet_wrap(~EpochBins, scales="free_x")+
  theme_classic()+ 
  #theme_gray() +
  theme(panel.border = element_rect(colour = "black", fill=NA))

HistCL <- PleiPlioCL %>%
  filter( !is.na(CL)) %>%
  filter(EpochBins != "Modern") %>%
  ggplot(aes(CL)) + geom_histogram(binwidth=10, col="black", fill="gray") + facet_wrap(~EpochBins, scales="free_x")+
  theme_classic()+ 
  #theme_gray() +
  theme(panel.border = element_rect(colour = "black", fill=NA))

HistCLModern
HistCL  

```


```{r "Species Accumulation Curve", echo=FALSE, message=FALSE, fig.cap="Species Accumulation Curve of fossil species per Locality and reference"}

vegan <- tidyCL %>%
  dplyr::select(Locality, Taxon) %>%
  group_by(Locality, Taxon) %>%
  summarise(n=n()) %>%
  tidyr::spread(Taxon, n, fill=0)

library(vegan)

#par(mfrow = c(2, 1))

vegan=vegan[,-1]
vegansp=specaccum(vegan,method="rarefaction", permutations=1000)
plot(vegansp,xlab="Ind",ylab="Richness", xvar="individuals", ci.type="line", ci.lty=2, ci.col="grey", col="deepskyblue4", lwd=2, main="Fossil species, CL, per Locality" )



vegan <- tidyCL %>%
  dplyr::select(Reference, Taxon) %>%
  group_by(Reference, Taxon) %>%
  summarise(n=n()) %>%
  tidyr::spread(Taxon, n, fill=0)

library(vegan)

vegan=vegan[,-1]
vegansp=specaccum(vegan,method="rarefaction", permutations=1000)
plot(vegansp,xlab="Ind",ylab="Richness", xvar="individuals", ci.type="line", ci.lty=2, ci.col="grey", col="deepskyblue4", lwd=2, main="Fossil species, CL, per Reference" )


```



```{r "Species Accumulation Curve with Genera", echo=FALSE, message=FALSE, fig.cap="Species Accumulation Curve of fossil genera per Locality and reference"}

vegan <- tidyCL %>%
  dplyr::select(Locality, Genus) %>%
  group_by(Locality, Genus) %>%
  summarise(n=n()) %>%
  tidyr::spread(Genus, n, fill=0)


#par(mfrow = c(2, 1))


vegan=vegan[,-1]
vegansp=specaccum(vegan,method="rarefaction", permutations=1000)
plot(vegansp,xlab="Ind",ylab="Richness", xvar="individuals", ci.type="line", ci.lty=2, ci.col="grey", col="deepskyblue4", lwd=2, main="Fossil genera, CL, per Locality" )


vegan <- tidyCL %>%
  dplyr::select(Reference, Genus) %>%
  group_by(Reference, Genus) %>%
  summarise(n=n()) %>%
  tidyr::spread(Genus, n, fill=0)

library(vegan)

vegan=vegan[,-1]
vegansp=specaccum(vegan,method="rarefaction", permutations=1000)
plot(vegansp,xlab="Ind",ylab="Richness", xvar="individuals", ci.type="line", ci.lty=2, ci.col="grey", col="deepskyblue4", lwd=2, main="Fossil genera, CL, per Reference")


```


```{r "Boxplots of each genus per time bin", echo=FALSE, fig.cap="Boxplots of each genus per time bin"}
PleiPlioCL$EpochBins = factor(PleiPlioCL$EpochBins, levels=c("Modern", "Holocene", "Upper Pleistocene",
                                                             "Middle Pleistocene", "Lower Pleistocene",
                                                             "Upper Pliocene", "Lower Pliocene",
                                                             "Upper Miocene"))

IndGenera <- PleiPlioCL %>%
  group_by(EpochBins, Genus) %>%
  filter(!is.na(CL)) %>%
  summarise(GenusMean=mean(CL), GenusSD=sd(CL), n=n()) 


BinGenera <- PleiPlioCL %>%
  group_by(EpochBins, Genus) %>%
  filter(!is.na(CL)) %>%
  summarise(GenusMean=mean(CL), GenusSD=sd(CL), n=n()) %>%
#  summarise(TimeBinMean=mean(GenusMean), TimeBinSD=sd(GenusMean), n=n()) %>%
  ungroup() %>%#, CL=CL
  ggplot(aes(EpochBins, GenusMean)) + #, colour=Genus
  theme_classic() +
  stat_boxplot(geom ='errorbar', width = 0.2) +
  geom_boxplot() +
  geom_pointrange(data=IndGenera, position="jitter", aes(x=EpochBins, y=GenusMean, colour=Genus, ymin = GenusMean-GenusSD, ymax = GenusMean+GenusSD)) +
  guides(color="none")
#  geom_text(data=IndGenera,aes(label=Genus, x=EpochBins, y=GenusMean))
#  geom_errorbar(data=IndGenera, position="jitter",aes(ymin = GenusMean-GenusSD, ymax = GenusMean+GenusSD, width=0.2, colour=Genus))#+
  #scale_color_brewer(palette="Set1")
  #scale_colour_gradientn(colours=rainbow(4))

BinGenera

```


```{r "Separate genera per time bin", echo=FALSE, fig.cap="Mean body size and standard deviation per genus in each time bin"}
BinGeneraFacet <- PleiPlioCL %>%
  group_by(EpochBins, Genus) %>%
  filter(!is.na(CL)) %>%
  summarise(GenusMean=mean(CL), GenusSD=sd(CL), n=n()) %>%
#  summarise(TimeBinMean=mean(GenusMean), TimeBinSD=sd(GenusMean), n=n()) %>%
  ungroup() %>%#, CL=CL
  ggplot(aes(EpochBins, GenusMean)) + #, colour=Genus
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
#  stat_boxplot(geom ='errorbar', width = 0.2) +
#  geom_boxplot() +
  geom_point(data=IndGenera,  aes(x=Genus, y=GenusMean, colour=Genus)) +
  geom_pointrange(data=IndGenera, aes(x=Genus, y=GenusMean, colour=Genus, ymin = GenusMean-GenusSD, ymax = GenusMean+GenusSD)) +
#  geom_text(data=IndGenera,aes(label=Genus, x=EpochBins, y=GenusMean)) +
  facet_wrap(~EpochBins, scales="free_x") +
  guides(colour="none")#+
#  stat_boxplot(data=BinGenera, geom ='errorbar', width = 0.2) +
#  geom_boxplot(data=BinGenera) 
#  geom_errorbar(data=IndGenera, position="jitter",aes(ymin = GenusMean-GenusSD, ymax = GenusMean+GenusSD, width=0.2, colour=Genus))#+
  #scale_color_brewer(palette="Set1")
  #scale_colour_gradientn(colours=rainbow(4))

BinGeneraFacet
```


\newpage

```{r "paleoTS, individuals, inluding island species", echo=FALSE}
PPCL <- PleiPlioCL %>%
  dplyr::select(CL, MeanBins) %>%
  dplyr::filter(CL != "NA") %>%
  mutate(tt= MeanBins) %>% # create mean age
  group_by(tt) %>% #create time bins
  summarise(mm=mean(CL), vv=var(CL), nn=n()) #create means etc. for each time bin 

PPCL[is.na(PPCL)]<-0 #subset NAs with O for n=1


sumTort <- read.csv("tortoises_summary.csv", sep=";", header=TRUE)

SumTort <- sumTort %>%
  mutate(tt=(Mamin+Mamax)/2, vv=sdCLmm^2, nn=n, mm=meanCLmm) %>%
  dplyr::select(mm, nn, vv, tt)
 
PPESCL <- bind_rows(SumTort,PPCL) #ExTort, 

combiCL <- PPESCL %>%
  dplyr::filter(tt==0.0000005) %>%   #maybe find a way to automatically filter double tt values...
  mutate(nx = nn*mm) %>%
  mutate(mmall=sum(nx)/sum(nn)) %>%
  mutate(SD=sqrt(nx), d=mm-mmall) %>%
  mutate(nsd=((nx^2+d^2)*nn)) %>%
  mutate(varall=sum(nsd)/sum(nn), n=sum(nn)) %>%
  dplyr::select(mm=mmall, vv=varall, nn=n, tt) %>%
  unique() %>%
  dplyr::select(mm, nn, vv, tt)


PPCL <- PPESCL %>%
  filter(tt !=0.0000005) %>%
  bind_rows(combiCL)%>%
  arrange(tt)

```

# including Island species  (n=`r sum(PPCL$nn)`)


```{r "paleoTS object", echo=FALSE}

kable(PPCL, caption="paleoTS object (mm= mean CL, nn = sample size, vv = variance (CL), tt = Age)")
```



```{r "paleoTS plot", echo=FALSE, fig.cap="individuals, including island species"}
library(paleoTS)
paleoPPCL <-as.paleoTS(PPCL$mm, PPCL$vv, PPCL$nn, PPCL$tt, MM = NULL, genpars = NULL, label = "Testudinidae body size evolution mode, Holocene-Upper Miocene, CL, including Island species")
#paleoPPCL
plot(paleoPPCL)


```



```{r "Model-fitting" , echo=FALSE}

kable(fit3models(paleoPPCL, silent=FALSE, method="AD", pool=FALSE), caption="Model-fitting results for testudinidae, individuals, including island species")
```



```{r "paleoTS plot with species mean, including island species", echo=FALSE, fig.cap="paleoTS plot with species mean, including island species"}
SpeciesMean <- PleiPlioCL %>%
  filter(EpochBins != "Modern") %>%
  group_by(EpochBins, Taxon, Age) %>%
  summarise(meanCL = mean(CL), n=n()) %>%
  merge(BINS)

SpeciesModern <- PleiPlioCL %>%
  filter(EpochBins == "Modern") %>%
  group_by(Taxon) %>%
  summarise(meanCL=mean(CL), sdCL=sd(CL), n=n(), Age=mean(Age), EpochBins=unique(EpochBins), MeanBins=unique(MeanBins))


SpeciesModern[is.na(SpeciesModern)]<-0 #subset NAs with O for n=1



SpeciesOverview <- SpeciesMean %>%
#  filter(EpochBins != "Modern") %>%
  filter( !is.na(meanCL)) %>%
  group_by(EpochBins) %>%
  summarise(meanSpeciesCL = mean(meanCL), nSpecies=n(), MeanBins = mean(MeanBins)) %>%
  arrange(MeanBins) 

kable(SpeciesOverview)



#####


SpeciesPaleo <- SpeciesMean %>%
  dplyr::select(meanCL, MeanBins) %>%
  dplyr::filter(meanCL != "NA") %>%
  mutate(tt= MeanBins) %>% # create mean age
  group_by(tt) %>% #create time bins
  summarise(mm=mean(meanCL), vv=var(meanCL), nn=n()) #create means etc. for each time bin 

#SpeciesPaleo[is.na(SpeciesPaleo)]<-0 #subset NAs with O for n=1


# ExTort <- extant %>%
#   mutate(CL = SCL * 10) %>%
#   dplyr::select(CL) %>%
#   summarise(mm=mean(CL), nn=n(), vv=var(CL), tt=0) %>%
#   dplyr::select(mm, nn, vv, tt)
# 
# ExTort[is.na(ExTort)] <- 0 #subset NAs with O for n=1

sumTort <- read.csv("tortoises_summary.csv", sep=";", header=TRUE)
#colnames(sumTort)[1] <- "Taxon"
colnames(sumTort)[6] <- "meanCL"
colnames(sumTort)[7] <- "sdCL"
#sumTort$EpochBins <- "Modern"
#sumTort$MeanBins <- 0.0000005


sumTortoises <- sumTort %>%
  mutate(Taxon= as.character(Species)) %>%
  mutate(MeanBins=(Mamin+Mamax)/2) %>%
  select(Taxon, MeanBins,  meanCL, sdCL) %>% #n,
  bind_rows(SpeciesModern)


SumTort <- sumTortoises %>%
  group_by(Taxon) %>%
  mutate(tt=MeanBins, vv=sdCL^2, nn=n, mm=meanCL) %>%
  dplyr::select(mm, nn, vv, tt, Taxon) %>%
  mutate(nx = nn*mm) %>%
  mutate(mmall=sum(nx)/sum(nn)) %>%
  mutate(SD=sqrt(nx), d=mm-mmall) %>%
  mutate(nsd=((nx^2+d^2)*nn)) %>%
  mutate(varall=sum(nsd)/sum(nn), n=sum(nn)) %>%
  dplyr::select(mm=mmall, vv=varall, nn=n, tt, Taxon) %>%
  unique() %>%
  dplyr::select(CL=mm, n=nn, var=vv, tt, Taxon)

# write.table(SumTort,file="SumTortModern.txt", sep="\t", row.names = FALSE) 

boxplot(SumTort$CL)


modernMean <- SumTort %>%
  ungroup() %>%
  select(CL, n, tt) %>%
  filter( !is.na(CL)) %>%
  group_by(tt) %>%
  summarise(mm = mean(CL), vv=var(CL), nn=n())

#bis hier alle modernen taxa zusammengefasst (summarised and MFN_testudinidae)



SpecPaleo <- bind_rows(modernMean,SpeciesPaleo) %>%
  arrange(tt)


kable(SpecPaleo)


paleoSpec <-as.paleoTS(SpecPaleo$mm, SpecPaleo$vv, SpecPaleo$nn, SpecPaleo$tt, MM = NULL, genpars = NULL, label = "Testudinidae body size evolution mode, Holocene-Upper Miocene, species mean CL", reset.time=TRUE)

plot(paleoSpec)

kable(fit3models(paleoSpec, silent=FALSE, method="AD", pool=FALSE))

```